---
- name: Restart loki
  ansible.builtin.systemd:
    name: loki
    state: restarted
    daemon_reload: true

- name: Restart loki-oauth2
  ansible.builtin.systemd:
    name: loki-oauth2
    state: restarted
    daemon_reload: true

...
